apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-metrics/deployment.yaml
  - victoria-metrics/service.yaml
  - victoria-metrics/pvc.yaml
  - vmagent/deployment.yaml
  - vmagent/configmap.yaml
  - vmagent/service.yaml
